
services:
  - type: web
    name: ultron-bot
    env: python
    region: frankfurt  # India ke liye closest free region
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot:app --workers 1 --bind 0.0.0.0:$PORT
