services:
  - type: web            # web service
    name: telegram-bot   # service ka naam
    env: python          # Python environment
    plan: free           # free tier
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
